import { Geist, Geist_Mono } from "next/font/google";
import SessionWrapper from "./component/SessionWrapper";
import Navbar from "/components/Navbar/page";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <main className="ml-[14vw] sm:ml-40 md:ml-64 flex-1 min-h-screen">{children}</main>
      </body>
      </SessionWrapper>
    </html>
  );
}
